import { Connection } from 'typeorm';
import { Factory, Seeder } from 'typeorm-seeding';

export class seedArtistsTable1607629586308 implements Seeder {
  public async run(factory: Factory, connection: Connection): Promise<void> {
    await connection.query('TRUNCATE TABLE artists CASCADE;');
    const descriptionHTML = `
      <p>LOREM – Reprehenderit sit sunt amet sunt in ad nostrud aute officia minim consectetur. Fugiat amet et ullamco nulla quis elit aliquip eiusmod. Ad qui nisi occaecat non aliquip incididunt ad commodo dolore et aliqua id ad. Pariatur commodo aute fugiat et cupidatat consectetur. Sint pariatur voluptate ut laboris aute aliqua mollit.</p>
      <h2>LOREM: Irure sint sint reprehenderit aute sit reprehenderit Lorem reprehenderit non mollit fugiat sint adipisicing elit.</h2>
      <p>Lorem Ad ullamco est labore reprehenderit occaecat. Veniam magna dolore dolore adipisicing non quis nostrud sint proident quis reprehenderit. Et tempor voluptate deserunt fugiat non adipisicing duis anim veniam magna consequat non excepteur laboris. Ut adipisicing cillum aliquip proident consequat aliquip nulla laborum irure pariatur est culpa quis aliqua. Commodo in veniam nisi amet ea est ex aute pariatur et nisi magna pariatur adipisicing.</p>
      <p>Eiusmod ullamco eiusmod excepteur sint in fugiat ipsum et esse esse.</p>
      <h2>Commodo quis consectetur aliquip nulla amet dolor tempor eu ad quis aliqua ullamco voluptate.</h2>
      <p>Est tempor proident exercitation qui amet elit cillum officia ullamco nostrud.</p>
      <ul><li>Consectetur;</li><li>Exercitation;</li><li>Cillum;</li><li>Nostrud;</li><li>Aliqua.</li></ul>
      <p>Ad labore officia est aute occaecat anim. Veniam exercitation labore in esse voluptate adipisicing reprehenderit exercitation cillum mollit dolor. Deserunt eiusmod occaecat aute tempor sint deserunt. Veniam laboris incididunt aliqua deserunt ea irure quis culpa anim reprehenderit culpa.</p>
      <p>Anim sit mollit sint dolor magna ut dolore sunt consequat officia incididunt ut.</p>
      <p><strong>Cupidatat est sint consequat laborum ad commodo exercitation quis commodo.</strong></p>
      <h2>Where to buy tickets for LOREM?</h2>
      <p>You can always buy tickets for Lorem concerts at Music.ua. Simple and convenient service - and tickets are already in your pocket!</p>`;
    const artists = [
      'ABBA',
      'AC/DC',
      'Aerosmith',
      'The Allman Brothers Band',
      'Amadou and Mariam',
      'The Andrews Sisters',
      'The Animals',
      'Arcade Fire',
      'The Band',
      'The Beach Boys',
      'The Beastie Boys',
      'The Beatles',
      'The Bee Gees',
      'Big Star',
      'Black Flag',
      'Black Sabbath',
      'Blondie',
      'Booker T. and the MG’s',
      'Boston',
      'The Boswell Sisters',
      'Boyz II Men',
      'Brooks & Dunn',
      'Buffalo Springfield',
      'The Byrds',
      'Calle 13',
      'The Chemical Brothers',
      'Chicago',
      'The Clash',
      'The Coasters',
      'Coldplay',
      'Alice Cooper',
      'Cream',
      'Creedence Clearwater Revival',
      'Crosby, Stills & Nash',
      'Daft Punk',
      'De La Soul',
      'Death Cab for Cutie',
      'The Decemberists',
      'Def Leppard',
      'Devo',
      'The Dillards',
      'Dion and the Belmonts',
      'Dire Straits',
      'Dixie Chicks',
      'The Doors',
      'The Drifters',
      'The Eagles',
      'Earth, Wind & Fire',
      'Emerson Lake & Palmer',
      'The Everly Brothers',
      'The Flamingos',
      'Fleetwood Mac',
      'The Flying Burrito Brothers',
      'The Four Seasons',
      'The Four Tops',
      'Fugazi',
      'The Gang of Four',
      'Genesis',
      'Grandmaster Flash and the Furious Five',
      'The Grateful Dead',
      'Green Day',
      'Guns N’ Roses',
      'Hüsker Dü',
      'The Hollies',
      'Iggy and the Stooges',
      'The Ink Spots',
      'The Isley Brothers',
      'The Jam',
      'The Jefferson Airplane',
      'The Jesus and Mary Chain',
      'Jonas Brothers',
      'Joy Division',
      'The Judds',
      'The Kingston Trio',
      'The Kinks',
      'Gladys Knight and the Pips',
      'Kool and the Gang',
      'Kraftwerk',
      'Ladysmith Black Mambazo',
      'Led Zeppelin',
      'Little Anthony and the Imperials',
      'The Louvin Brothers',
      'Love',
      'The Lovin’ Spoonful',
      'Frankie Lymon and the Teenagers',
      'Lynyrd Skynyrd',
      'The MC5',
      'The Mamas and the Papas',
      'The Mekons',
      'Metallica',
      'The Mills Brothers',
      'Modest Mouse',
      'The Monkees',
      'The Moody Blues',
      'The Moonglows',
      'Mumford & Sons',
      'My Chemical Romance',
      'New Order',
      'The New York Dolls',
      'Nine Inch Nails',
      'Nirvana',
      'The O’Jays',
      'The Ohio Players',
      'One Direction',
      'The Orioles',
      'OutKast',
      'Parliament-Funkadelic',
      'Pavement',
      'Pearl Jam',
      'Pere Ubu',
      'The Pet Shop Boys',
      'Peter, Paul and Mary',
      'Pink Floyd',
      'Pixies',
      'The Platters',
      'Poco',
      'The Police',
      'Portishead',
      'Public Enemy',
      'Puffy AmiYumi',
      'Queen',
      'R.E.M.',
      'Radiohead',
      'Rage Against the Machine',
      'The Ramones',
      'Rascal Flatts',
      'Red Hot Chili Peppers',
      'The Replacements',
      'The Rolling Stones',
      'Roxy Music',
      'Run-D.M.C.',
      'Sam and Dave',
      'Santana',
      'The Sex Pistols',
      'The Shadows',
      'The Shirelles',
      'Sleater-Kinney',
      'Sly and the Family Stone',
      'Smashing Pumpkins',
      'The Smiths',
      'Sonic Youth',
      'The Soul Stirrers',
      'Spice Girls',
      'Stanley Brothers',
      'The Staple Singers',
      'Steely Dan',
      'The Strokes',
      'TV on the Radio',
      'Talking Heads',
      'Television',
      'The Temptations',
      'Tinariwen',
      'Toots and the Maytals',
      'Traffic',
      'The Turtles',
      'U2',
      'Van Halen',
      'The Velvet Underground',
      'The Ventures',
      'The Weavers',
      'The White Stripes',
      'The Who',
      'Wilco',
      'X',
      'The Yardbirds',
      'Yes',
      'Yo La Tengo',
      'ZZ Top',
    ].map(artistName => ({ name: artistName, descriptionHTML }));
    await connection
      .createQueryBuilder()
      .insert()
      .into('artists')
      .values(artists)
      .execute();
  }
}
